// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO2sEyoB1eJbOrCAqC5IgLhbtKqRETZK4',
    appId: '1:680227279071:web:83a3f96cea0ab65fd4196a',
    messagingSenderId: '680227279071',
    projectId: 'flutter-and-firebase-7aug8-pm',
    authDomain: 'flutter-and-firebase-7aug8-pm.firebaseapp.com',
    databaseURL: 'https://flutter-and-firebase-7aug8-pm-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-and-firebase-7aug8-pm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX3WbUDRFWsTXQ87T6PWbUFCLSa3jjlpw',
    appId: '1:680227279071:android:a17f6d5d23a9ff22d4196a',
    messagingSenderId: '680227279071',
    projectId: 'flutter-and-firebase-7aug8-pm',
    databaseURL: 'https://flutter-and-firebase-7aug8-pm-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-and-firebase-7aug8-pm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE0BTd3nsdKI-Ve2EJmzGEPmXgtFDrfx0',
    appId: '1:680227279071:ios:7e0b370b52c6e432d4196a',
    messagingSenderId: '680227279071',
    projectId: 'flutter-and-firebase-7aug8-pm',
    databaseURL: 'https://flutter-and-firebase-7aug8-pm-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-and-firebase-7aug8-pm.firebasestorage.app',
    androidClientId: '680227279071-u131ib3m2r37dmp16tgnh2pthg0cefep.apps.googleusercontent.com',
    iosClientId: '680227279071-tnfq3s9d78lbov30gb76anv0ug7ft9j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.soundscape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE0BTd3nsdKI-Ve2EJmzGEPmXgtFDrfx0',
    appId: '1:680227279071:ios:7e0b370b52c6e432d4196a',
    messagingSenderId: '680227279071',
    projectId: 'flutter-and-firebase-7aug8-pm',
    databaseURL: 'https://flutter-and-firebase-7aug8-pm-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-and-firebase-7aug8-pm.firebasestorage.app',
    androidClientId: '680227279071-u131ib3m2r37dmp16tgnh2pthg0cefep.apps.googleusercontent.com',
    iosClientId: '680227279071-tnfq3s9d78lbov30gb76anv0ug7ft9j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.soundscape',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlihdNTrD0FwpX7WVyuRlKN_7vO4N_2Ug',
    appId: '1:680227279071:web:bda560ca176ca17ad4196a',
    messagingSenderId: '680227279071',
    projectId: 'flutter-and-firebase-7aug8-pm',
    authDomain: 'flutter-and-firebase-7aug8-pm.firebaseapp.com',
    databaseURL: 'https://flutter-and-firebase-7aug8-pm-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-and-firebase-7aug8-pm.firebasestorage.app',
  );

}